#!/bin/bash

### parameters
OUTFOLDER="test/"
I=${OUTFOLDER}I_1.bool
R=${OUTFOLDER}R_1.bool
J=${OUTFOLDER}I_2.bool
S=${OUTFOLDER}R_2.bool
k=3
P=${OUTFOLDER}P.hq
QCIR_OUT=${OUTFOLDER}HQ.qcir
QS="AA"
SEM="PES"
ENCODING="NN"


# execute bin/genqbf with the input parameters, the output should be one file named HQ.qcir generated by this bin and place in test/ folder
./bin/genqbf -I ${I} -R ${R} -J ${J} -S ${S} -P ${P} -k ${k} -F ${QS} -f qcir -o ${QCIR_OUT} -sem ${SEM} -n --fast -new ${ENCODING}

# ./bin/genqbf -I test/I_1.bool -R test/R_1.bool -J test/I_2.bool -S test/R_2.bool -P test/P.hq -k 3 -F AA -f qcir -o test/HQ.qcir -sem PES -n --fast -new NN
